Testing what epsilon values are returned when attack is applied to unprotected data (i.e., the only protection is sampling variability). This file uses the locations of COVID-19 patients from South Korea.

In [1]:
# first we need to import some dependencies.
import pandas as pd
from sklearn.model_selection import train_test_split

# import privacy attack
# !pip install git+https://github.com/GilianPonte/likelihood_based_privacy_attack.git
from likelihood_based_privacy_attack import attacks

# we read public churn data
url = 'https://raw.githubusercontent.com/albayraktaroglu/Datasets/master/churn.csv'
churn = pd.read_csv(url, index_col=0)

# select some variables
churn = churn.iloc[:,6:15]
samples = 300 # select the number of observations
churn = pd.DataFrame.drop_duplicates(churn) # drop duplicates

Define swapping protection function.

In [2]:
# define our data protected method. We use swapping 25% of the observations.
def swapping(percent, data):
  import random
  import numpy as np
  swap_data = data
  idx = random.randint(0,data.shape[1]) # pick a random variable
  variable = np.array(data.iloc[:,idx]) # select variable from data
  ix_size = int(percent * len(variable) * 0.5) # select proportion to shuffle
  ix_1 = np.random.choice(len(variable), size=ix_size, replace=False) # select rows to shuffle
  ix_2 = np.random.choice(len(variable), size=ix_size, replace=False) # select rows to shuffle
  b1 = variable[ix_1] # take rows from variable and create b
  b2 = variable[ix_2] # take rows from variable and create b

  variable[ix_2] = b1 # swap 1
  variable[ix_1] = b2 # swap 2

  swap_data.iloc[:,idx] = variable  # place variable back in original data
  return swap_data

In [3]:
# here we create the train, adversary and outside_training set.
churn, evaluation_outside_training = train_test_split(churn, train_size = int(samples*2/3), test_size = int(samples*1/3)) 
train, adversary_training = train_test_split(churn, train_size = int(samples*1/3))

Apply privacy attack to unprotected churn data (Gilian's example data set).

In [4]:
attacks.privacy_attack(seed=1,
                       simulations=10,
                       train=train,
                       adversary=adversary_training,
                       outside_training=evaluation_outside_training,
                       protected_training=train,
                       protected_adversary=adversary_training)

iteration is 0


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 1
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 2
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 3
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 4


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 5
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 6
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 7
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 8
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf
iteration is 9
FPR is 0.51
FNR is 0.0
TPR is 1.0
TNR is 0.49
empirical epsilon = inf


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

(array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]),
 0.51,
 0.49,
 0.0,
 1.0)

Using unprotected data returns infinite epsilon, which is expected.

Let's test whether the same is true for the SK data. We'll do two cases - one with a very small number of observations, and one with the actual number of observations.

In [5]:
# import data and drop duplicates
sk_data = pd.read_csv("../../Data/SK/cleaned_sk_data.csv")
sk_data = pd.DataFrame.drop_duplicates(sk_data) # drop duplicates

In [6]:
sk_data

latitude  longitude  sex  age  state
0     0.944157  -1.010655    1    5      0
1     0.889746  -0.694899    1    5      0
2     0.917482  -0.682299    1    3      0
3     0.916660  -0.682551    1    3      0
4     0.886074  -0.668883    1    3      0
...        ...        ...  ...  ...    ...
6701 -1.662973   1.164819    1    2      0
6703 -1.558049   0.964307    1    6      0
6704 -1.622048   0.866628    1    6      0
6709 -1.548071   1.557316    1    4      0
6710 -1.549392   1.555785    1    4      0

[3807 rows x 5 columns]

In [7]:
# here we create the train, adversary and outside_training set.
sk_data, evaluation_outside_training = train_test_split(sk_data, train_size = int(samples*2/3), test_size = int(samples*1/3)) 
train, adversary_training = train_test_split(sk_data, train_size = int(samples*1/3))

Apply privacy attack.

In [8]:
attacks.privacy_attack(seed=1,
                       simulations=10,
                       train=train,
                       adversary=adversary_training,
                       outside_training=evaluation_outside_training,
                       protected_training=train,
                       protected_adversary=adversary_training)

/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

iteration is 0
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 1
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 2
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 3


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 4
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 5
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 6


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 7
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 8
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf
iteration is 9
FPR is 0.72
FNR is 0.0
TPR is 1.0
TNR is 0.28
empirical epsilon = inf


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(

(array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]),
 0.72,
 0.28,
 0.0,
 1.0)

We get infinite epsilon values as expected.

What if we apply swapping protection to the SK data with the small number of observations?

In [9]:
# apply protection to train and adversary
swap25_train = swapping(percent = 0.25, data = train) # apply swapping 25% to train
swap25_adversary_training = swapping(percent = 0.25, data = adversary_training)  # apply swapping 25% to adv

In [10]:
attacks.privacy_attack(seed=1,
                       simulations=10,
                       train=train,
                       adversary=adversary_training,
                       outside_training=evaluation_outside_training,
                       protected_training=swap25_train,
                       protected_adversary=swap25_adversary_training)

iteration is 0
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 1
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 2


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 3
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 4
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 5


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 6
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 7
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 8
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf
iteration is 9
FPR is 0.71
FNR is 0.0
TPR is 1.0
TNR is 0.29000000000000004
empirical epsilon = inf


/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  print("empirical epsilon = " + str(max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))))
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:41: RuntimeWarning: divide by zero encountered in scalar divide
  epsilons = np.append(epsilons,max(math.log((1 - (1/N) - FPR)/FNR), math.log((1 - (1/N) - FNR)/FPR))) # append resulting epsilon to epsilons
/opt/anaconda3/lib/python3.12/site-packages/likelihood_based_privacy_attack/attacks.py:46: RuntimeWarning: divide by zero encountered in scalar divide
  p

(array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]),
 0.71,
 0.29000000000000004,
 0.0,
 1.0)

Infinite epsilon values, as expected.

What about when we use the full SK data?

In [11]:
# here we import the external data, train data and adversary training data (unprotected)
sk_data = pd.read_csv("../../Data/SK/cleaned_sk_data.csv")

In [12]:
sk_data

latitude  longitude  sex  age  state
0     0.944157  -1.010655    1    5      0
1     0.889746  -0.694899    1    5      0
2     0.917482  -0.682299    1    3      0
3     0.916660  -0.682551    1    3      0
4     0.886074  -0.668883    1    3      0
...        ...        ...  ...  ...    ...
6707  0.881500  -0.925307    1    4      0
6708 -1.728784   1.470871    1    4      0
6709 -1.548071   1.557316    1    4      0
6710 -1.549392   1.555785    1    4      0
6711 -1.548071   1.557316    1    4      0

[6712 rows x 5 columns]

We have increased to about 6700 rows.

In [13]:
# here we create the train, adversary and outside_training set.
sk_data, evaluation_outside_training = train_test_split(sk_data, train_size = int(sk_data.shape[0]*2/3), test_size = int(sk_data.shape[0]*1/3)) 
train, adversary_training = train_test_split(sk_data, train_size = int(sk_data.shape[0]*1/3))

In [14]:
attacks.privacy_attack(seed=1,
                       simulations=10,
                       train=train,
                       adversary=adversary_training,
                       outside_training=evaluation_outside_training,
                       protected_training=train,
                       protected_adversary=adversary_training)

iteration is 0
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 1
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 2
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 3
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 4
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 5
FPR is 0.4228877961555655
FNR is 0.40576794097920854
TPR is 0.5942320590207915
TNR is 0.5771122038444345
empirical epsilon = 0.3405657310462579
iteration is 6
FPR is 0.4228877961555655
FNR i

(array([0.34056573, 0.34056573, 0.34056573, 0.34056573, 0.34056573,
        0.34056573, 0.34056573, 0.34056573, 0.34056573, 0.34056573]),
 0.4228877961555655,
 0.5771122038444345,
 0.40576794097920854,
 0.5942320590207915)

Now the epsilon values are much smaller. Does this imply sufficient protection from sampling variability?

Apply swapping to the full SK data.

In [15]:
# apply protection to train and adversary
swap25_train = swapping(percent = 0.25, data = train) # apply swapping 25% to train
swap25_adversary_training = swapping(percent = 0.25, data = adversary_training)  # apply swapping 25% to adv

In [16]:
attacks.privacy_attack(seed=1,
                       simulations=10,
                       train=train,
                       adversary=adversary_training,
                       outside_training=evaluation_outside_training,
                       protected_training=swap25_train,
                       protected_adversary=swap25_adversary_training)

iteration is 0
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 1
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 2
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 3
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 4
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 5
FPR is 0.4152883325882879
FNR is 0.40509725016767273
TPR is 0.5949027498323273
TNR is 0.5847116674117121
empirical epsilon = 0.3554549405629998
iteration is 6
FPR is 0.4152883325882879
FNR i

(array([0.35545494, 0.35545494, 0.35545494, 0.35545494, 0.35545494,
        0.35545494, 0.35545494, 0.35545494, 0.35545494, 0.35545494]),
 0.4152883325882879,
 0.5847116674117121,
 0.40509725016767273,
 0.5949027498323273)

Swapping seems to have slightly increased the privacy risk based on slightly larger epsilon values.